In [1]:
import numpy as np

# Append

In [2]:
# append values to ndarray
a = np.array([[1,2],
             [3,4]])
print(a)
b = np.append(a,[[5,6]],axis=0)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


# Broadcasting in NumPy arrays

Broadcasting is one of the best features of ndarrays. It lets you perform arithmetics operations between ndarrays of different sizes or between an ndarray and a simple number!

Broadcasting essentially stretches the smaller ndarray so that it matches the shape of the larger ndarray:

In [4]:
a = np.arange(10,20,2)
b = np.array([[2],[3]])
print(a)
print(b)
print('Adding two different size arrays :','\n',a+b)
print('Multiplying an ndarray and a number :',a*2)

[10 12 14 16 18]
[[2]
 [3]]
Adding two different size arrays : 
 [[12 14 16 18 20]
 [13 15 17 19 21]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [5]:
a = np.ones((3,3))
print(a)
b = np.array([2])
print(b)
print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


Here, the second ndarray was stretched, hypothetically, to a 3 x 3 shape, and then the result was calculated.

# Maths with NumPy arrays
Basic arithmetic operations on NumPy arrays

The basic arithmetic operations can easily be performed on NumPy arrays. 


In [6]:
a = np.array([1,2,3,4,5,6])
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [-4 -3 -2 -1  0  1]
Multiply : [ 5 10 15 20 25 30]
Divide : [0.2 0.4 0.6 0.8 1.  1.2]
Power : [ 1  4  9 16 25 36]
Remainder : [1 2 3 4 0 1]


# Mean, Median and Standard deviation

To find the mean and standard deviation of a NumPy array, use the mean(), std() and median() methods:

In [7]:
a = np.arange(5,15,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

[ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [8]:
l=np.array([[1,2,3],[4,5,6]])

In [9]:
o=np.array([[2,2,4],[6,8,9]])

In [10]:
l+o

array([[ 3,  4,  7],
       [10, 13, 15]])

In [11]:
l-o

array([[-1,  0, -1],
       [-2, -3, -3]])

In [12]:
u=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype = float)
print(u)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [13]:
u>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [14]:
u[u>5]

array([ 6.,  7.,  8.,  9., 10., 11., 12.])

In [15]:
u**2

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.]])

In [16]:
pow(u,2)

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.]])

In [17]:
u**4

array([[1.0000e+00, 1.6000e+01, 8.1000e+01, 2.5600e+02],
       [6.2500e+02, 1.2960e+03, 2.4010e+03, 4.0960e+03],
       [6.5610e+03, 1.0000e+04, 1.4641e+04, 2.0736e+04]])

# Min-Max values and their indexes

Min and Max values in an ndarray can be easily found using the min() and max() methods:

axis=0: Apply operation column-wise, across all rows for each column.
    
axis=1: Apply operation row-wise, across all columns for each row.

In [18]:
a = np.array([[1,6,5],[4,3,7]])
print(a)
# minimum along a row
print('Min :',np.min(a,axis=1))
# maximum along a column
print('Max :',np.max(a,axis=0))

[[1 6 5]
 [4 3 7]]
Min : [1 3]
Max : [4 6 7]


Determine the index of the minimum or maximum value in the ndarray along a particular axis using the argmin() and argmax() methods:

In [19]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
print("\nIndices of Max element : ", np.argmax(array, axis=0))
print("\nIndices of Max element : ", np.argmax(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Indices of Max element :  [2 2 2 2]

Indices of Max element :  [3 3 3]


In [20]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
# as per the indices
print("\nIndices of Min element : ", np.argmin(array, axis=0))
print("\nIndices of Min element : ", np.argmin(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Indices of Min element :  [0 0 0 0]

Indices of Min element :  [0 0 0]


# More functions

In [21]:
mat1 = np.array(np.random.randint(1,10,9)).reshape(3,3)#Creating random Numpy array of size 3x3

In [22]:
mat1

array([[5, 2, 6],
       [8, 1, 2],
       [7, 5, 2]])

In [23]:
np.min(mat1)    #minimum

1

In [24]:
np.max(mat1)    #maximum

8

In [25]:
np.sqrt(mat1)   #Sq-root of 1st matrix

array([[2.23606798, 1.41421356, 2.44948974],
       [2.82842712, 1.        , 1.41421356],
       [2.64575131, 2.23606798, 1.41421356]])

In [26]:
np.log10(mat1)  #log 10

array([[0.69897   , 0.30103   , 0.77815125],
       [0.90308999, 0.        , 0.30103   ],
       [0.84509804, 0.69897   , 0.30103   ]])

In [27]:
np.mean(mat1)   #mean

4.222222222222222

In [28]:
np.median(mat1) #median

5.0

In [29]:
np.var(mat1)    #variance

5.728395061728396

In [30]:
np.std(mat1)    #standard deviation

2.3934065809486684

# Sorting in NumPy arrays

In [31]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a = np.array([[1,4,2,5],[6,8,7,9]])
np.sort(a)

array([[1, 2, 4, 5],
       [6, 7, 8, 9]])

# You don’t need to memorize the name of a module or function. You can always search on the web about a specific module or you can refer to class notebooks. Although, once you start coding on a particular programming language after spending particular time, you will start remembering the names which you often use.